title: Товары
single: Product
model: Product
fields:
  id:
    title: Id
    readonly: true
    type: text
  id_category:
    title: Категория
    type: select
  title:
    title: Заголовок
    type: text
  _slug:
    title: Символьный код
    type: text
  image:
    title: Основное изображение
  other_images:
    title: Доп. изображения
    type: photogallery
    multiple: true
    model: ProductImage
    field_name: other_images
    action: upload_image
    filename: image
  description:
    title: Описание
    type: rich
  description_short:
    title: Описание краткое
    type: area
  id_brand:
    title: Производитель
    type: select
  price:
    title: Цена
    type: text
  discount:
    title: Скидка,%
    type: text
  price_old:
    title: Старая цена
    type: text
  rating:
    title: Рейтинг
    type: text
  is_top:
    title: Популярный товар
    type: checkbox
  is_new:
    title: Новинка
    type: checkbox
  is_recommended:
    title: Рекоммендуемый товар
    type: checkbox
  _created_at:
    title: Создан
    type: datepicker
    timepicker: true
    readonly: true
  _updated_at:
    title: Изменен
    type: datepicker
    timepicker: true
    readonly: true
  _meta_title:
    title: Meta-Заголовок
    type: text
  _meta_description:
    title: Meta-Описание
    type: area
  _meta_keywords:
    title: Meta-Ключевые слова
    type: area
  product_properties:
    title: Свойства
    type: product_property
  empty_product_properties:
    title: Свойства
    type: empty_product_properties
sort: '_created_at DESC'
tabs:
  prices:
    title: Цена
    fields: [price, price_old, discount]
  properties:
    title: Свойства
    fields: [id_brand, rating, is_top, is_recommended, is_new]
  other_properties:
    title: Доп. свойства
    fields: [product_properties, empty_product_properties]
  metas:
    title: Мета-данные
    fields: [_meta_title,_meta_description,_meta_keywords]
actions:
  list:
    fields: [id, title, id_category, id_section, _slug, image]
  delete: true
  edit:
    hide: [id, _created_at, _updated_at, empty_product_properties]
  add:
    hide: [id, _created_at, _updated_at, product_properties]
